### ISSUE TITLE
add_track_playlist

### ISSUE THREAD

**Issue by maexrock** [NcVillalobos/DeezerPy#1]
Hi,

neat and clean API-wrapper so far and already introduced in a mini-project of mine.

What i have missed was a function for adding a track to a playlist (https://developers.deezer.com/api/playlist/tracks).

Here is a steep template (could be added to class Deezer):

def add_track_playlist(self, playlist_id, track_id):
    """
    Add a track to a user's playlist
    :param playlist_id: ID or URL
    :param track_id: ID or URL
    """
    playlistid = self._get_id("playlist", playlist_id)
    trackid = self._get_id("track", track_id)
    return self._post(f"playlist/{playlistid}/tracks", "songs", `trackid)

Thanks & BR
maexrock

**Comment by NcVillalobos** [comment]
Hi @maexrock,

First of all, I would like to thank you for using my library and I hope it is being useful for your projects.

Regarding your suggestion, I have just implemented it on the code as suggested. 

Many thanks & best regards
